### ISSUE TITLE
rtcon: 'module' object has no attribute 'any'

### ISSUE THREAD

**Issue by n-kawauchi** [gbiggs/rtctree#7]
rtconで接続できません。

$ rtls localhost/ubuntu1510-64.host_cxt/
ConsoleIn0.rtc  ConsoleOut0.rtc

$ rtcon -v localhost/ubuntu1510-64.host_cxt/ConsoleIn0.rtc:out localhost/ubuntu1510-64.host_cxt/ConsoleOut0.rtc:in
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rtshell/rtcon.py", line 117, in main
    connect_ports(paths, options, tree=tree)
  File "/usr/local/lib/python2.7/dist-packages/rtshell/rtcon.py", line 66, in connect_ports
    props=options.properties)
  File "/usr/local/lib/python2.7/dist-packages/rtctree/ports.py", line 316, in connect
    props=new_props)
  File "/usr/local/lib/python2.7/dist-packages/rtctree/ports.py", line 115, in connect
    props = utils.dict_to_nvlist(props)
  File "/usr/local/lib/python2.7/dist-packages/rtctree/utils.py", line 166, in dict_to_nvlist
    result.append(SDOPackage.NameValue(item, omniORB.any.to_any(dict[item])))
AttributeError: 'module' object has no attribute 'any'
rtcon: 'module' object has no attribute 'any'

**Comment by gbiggs** [comment]
Fixed by #4 3c4ef12ac5c76f30499f1
